### ISSUE TITLE
RPS v2.3.2 crashes with missing 'chalk' module

### ISSUE THREAD

**Issue by DennisSchwartz** [repositive/rps#17]
I've updated rps using `npm i -g @repositive/rps` and then ran `rps gen -y`.

That command crashed and so did any subsequent rps call with this error:

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dennis/.nvm/versions/node/v8.2.1/lib/node_modules/@repositive/rps/dist/main/gen/index.js:11:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

![image](https://user-images.githubusercontent.com/2827690/32493082-7dfa747a-c3b4-11e7-8e07-243054927c8b.png)

**Comment by DennisSchwartz** [comment]
Running `npm link rps` after installing rps fixed the issue.

**Comment by DennisSchwartz** [comment]
Wait is this right??

![image](https://user-images.githubusercontent.com/2827690/32493234-068878dc-c3b5-11e7-9658-4946294a9c7c.png)

**Comment by DennisSchwartz** [comment]
It still doesn't work, now a different error:
![image](https://user-images.githubusercontent.com/2827690/32493258-1c808ba2-c3b5-11e7-8190-0bb2d27f76fc.png)
